---
- name: add distribution-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: add Debian Wheezy workaround
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
  when: (ansible_distribution == "Debian") and (ansible_distribution_release == "wheezy")

- name: install unattended-upgrades
  apt:
    pkg: unattended-upgrades
    state: present
    cache_valid_time: "{{unattended_cache_valid_time}}"
    update_cache: yes

- name: install reboot dependencies
  include: reboot.yml
  when: unattended_automatic_reboot|bool

- name: create Apt auto-upgrades & unattended-upgrades configuration
  template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/90-ansible-unattended-upgrades
    owner: root
    group: root
    mode: 0644
